project:
  type: website
  render:
    - index.qmd
    - story.qmd
    - analysis.qmd

website:
  title: "NCAA Volleyball: Experience vs Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: The Veteran Advantage
      - href: analysis.qmd
        text: Stats Comparison

format:
  html:
    theme: cosmo
    toc: true
